name: Deploy

on: [push]

jobs:
  deploy:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: scp-deployer
      uses: actions/checkout@v2    
    - name: Upload Files
      uses: siva1024/scp-deployer@v1.0
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
      with:
        source: "site/*"
        target: "/www/pruebas-deploy"
        strip_components: 1