name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASS }}
        localDir: "/"
        remoteDir: "/pruebas-deploy"
        strip_components: 1