name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.PASS }}
        localDir: "/"
        remoteDir: "/www/pruebas-deploy"
        options: "--delete --asci"