name: Deploy

on: [push]

jobs:
  deploy:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2    
    - name: Upload Files
      uses: siva1024/scp-deployer@latest
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        source: "site/*"
        target: "/www/pruebas-deploy"
        strip_components: 1